NOSTORY: First S3 module commit
boldlink/terraform-aws-s3 pull request #1
Opened 2022-02-24 20:45 UTC by patrickmukumbu

PR for AWS S3 terraform module

2022-02-24 23:11 UTC, hugoalmeida264 commented
@patrickmukumbu please lock this module for the aws provider < 4.0.0 see this document
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade 
We will need to refactor the s3 to make it compatible with 4.x.x+ versions ;) 

cc @JohnNMwangi

2022-03-03 12:09 UTC, JohnNMwangi requested changes

2022-03-03 12:09 UTC, JohnNMwangi commented on README.md
> +Example available [here](https://github.com/boldlink/terraform-aws-ec2/tree/main/examples/main.tf)
Hey @patrickmukumbu , do you have an example for this module?

2022-03-03 15:34 UTC, JohnNMwangi requested changes

2022-03-03 15:34 UTC, JohnNMwangi commented on README.md
> +| <a name="input_environment"></a> [environment](#input\_environment) | The environemnt this resource is belongs to | `string` | `null` | no |
minor typo here.

2022-03-04 08:50 UTC, JohnNMwangi approved these changes

2022-03-04 11:05 UTC, merged